chain_width = 80
comment_width = 80
edition = "2021"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
merge_derives = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
wrap_comments = true